[package]
name = "tEtcher"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
crossterm = "0.27"

# Required only for Windows builds
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winbase"] }


